# Generated by Django 3.0.6 on 2020-06-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='release_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='auto',
            name='renter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auto_renters', to='api.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='citizenship',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='repeated_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='auto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='request_autos', to='api.Auto'),
        ),
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='rent_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='renter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='request_renters', to='api.Client'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
