# Generated by Django 3.0.6 on 2020-06-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200602_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='release_year',
            field=models.IntegerField(default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='renter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_renters', to='api.Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='citizenship',
            field=models.CharField(default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='repeated_client',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='auto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_autos', to='api.Auto'),
        ),
        migrations.AlterField(
            model_name='request',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='rent_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='renter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_renters', to='api.Client'),
        ),
    ]
