# Generated by Django 3.0.7 on 2020-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200602_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='pictures'),
        ),
    ]
