# Generated by Django 3.0.7 on 2020-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='first_payment',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
