# Generated by Django 3.0.7 on 2020-06-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_request_first_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
